INSERT INTO "Project" (
    "id",
    "code",
    "name",
    "portfolio",
    "sponsor",
    "projectManager",
    "status",
    "rag",
    "startDate",
    "targetDate",
    "budgetPlanned",
    "budgetForecast",
    "scheduleVariance",
    "progress",
    "summary",
    "sortOrder",
    "createdAt",
    "updatedAt"
)
VALUES
    (
        'test_project_002',
        'TEST-002',
        'Второй тестовый проект',
        'Project Management',
        'CIO',
        'Петров П.П.',
        'ACTIVE'::"ProjectStatus",
        'AMBER'::"RagStatus",
        '2026-06-01T00:00:00.000Z'::timestamp,
        '2026-10-15T00:00:00.000Z'::timestamp,
        18000000.00,
        19200000.00,
        5,
        35,
        'Тестовый проект с умеренными рисками по срокам и уточняемым объемом работ.',
        20,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'test_project_003',
        'TEST-003',
        'Третий тестовый проект',
        'Project Management',
        'COO',
        'Сидорова М.М.',
        'ACTIVE'::"ProjectStatus",
        'GREEN'::"RagStatus",
        '2026-03-10T00:00:00.000Z'::timestamp,
        '2026-07-30T00:00:00.000Z'::timestamp,
        24000000.00,
        23100000.00,
        -3,
        72,
        'Тестовый проект идет лучше baseline и подходит для проверки статуса Green.',
        30,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'test_project_004',
        'TEST-004',
        'Четвертый тестовый проект',
        'Project Management',
        'CFO',
        'Кузнецов И.И.',
        'ACTIVE'::"ProjectStatus",
        'RED'::"RagStatus",
        '2026-04-20T00:00:00.000Z'::timestamp,
        '2026-12-20T00:00:00.000Z'::timestamp,
        32000000.00,
        38900000.00,
        21,
        18,
        'Тестовый проект в критическом статусе для проверки переключения и executive overview.',
        40,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
ON CONFLICT ("code") DO UPDATE
SET
    "parentId" = NULL,
    "name" = EXCLUDED."name",
    "portfolio" = EXCLUDED."portfolio",
    "sponsor" = EXCLUDED."sponsor",
    "projectManager" = EXCLUDED."projectManager",
    "status" = EXCLUDED."status",
    "rag" = EXCLUDED."rag",
    "startDate" = EXCLUDED."startDate",
    "targetDate" = EXCLUDED."targetDate",
    "budgetPlanned" = EXCLUDED."budgetPlanned",
    "budgetForecast" = EXCLUDED."budgetForecast",
    "scheduleVariance" = EXCLUDED."scheduleVariance",
    "progress" = EXCLUDED."progress",
    "summary" = EXCLUDED."summary",
    "sortOrder" = EXCLUDED."sortOrder",
    "updatedAt" = CURRENT_TIMESTAMP;
