import type { WbsItemStatus, WbsItemType } from "./domainTypes";
import type { WbsTableColumnKey } from "./wbsTable";

export const WBS_COLUMN_EN_LABELS: Record<WbsTableColumnKey, string> = {
  level: "Level",
  structure: "Structure",
  type: "Type",
  status: "Status",
  owner: "Assignee",
  start: "Start",
  due: "Due date",
  workDays: "Work days",
  calendarDays: "Calendar days",
  calendar: "Calendar",
  effortPercent: "Effort, %",
  progress: "%",
  jiraTicketUrl: "Jira URL",
  predecessor1: "Predecessor 1",
  predecessor2: "Predecessor 2",
  predecessor3: "Predecessor 3",
  predecessor4: "Predecessor 4",
  predecessor5: "Predecessor 5",
  predecessor6: "Predecessor 6",
  leadLag: "Offset",
};

export const WBS_TYPE_EN_LABELS: Record<WbsItemType, string> = {
  PHASE: "Phase",
  WORK_PACKAGE: "Work package",
  DELIVERABLE: "Result",
  MILESTONE: "Milestone",
  GOAL: "Goal",
  TASK: "Task",
};

export const WBS_STATUS_EN_LABELS: Record<WbsItemStatus, string> = {
  NOT_STARTED: "Not started",
  IN_PROGRESS: "In progress",
  IN_REVIEW: "In review",
  AT_RISK: "At risk",
  BLOCKED: "Failed",
  DONE: "Done",
  CANCELLED: "Cancelled",
};

const SERIES_9000_WBS_TITLE_BY_CODE: Record<string, string> = {
  "1": "Project launch",
  "1.1.1": "First board samples received",
  "1.1.2": "Initial firmware build",
  "1.1.3": "Initial board tests",
  "1.1.4": "Fix initial issues",
  "1.1.5": "Patch synchronization",
  "1.1.6": "Epics, labels, filters, project passport, etc.",
  "1.1.7": "Initial Jenkins setup",
  "1.1.8": "Sample planning",
  "1.1.9": "TV team kick-off",
  "1.1.10": "Functional requirements",
  "1.1.11": "SD - CVTE - CH kick-off",
  "1.1.12": "Agree with the Chinese team on samples",
  "1.1.13": "Get HW and SW milestones from the Chinese team",
  "1.1.14": "Align resources and project priority",
  "1.1.15": "Prepare the baseline project plan and risks",
  "1.1.16": "Project launched",
  "2": "Hardware",
  "2.1.1": "Hardware documentation package",
  "2.1.2": "Documentation review",
  "2.1.3": "Approval of new microphones",
  "2.1.4": "Approval of antennas",
  "2.2": "FF board",
  "2.2.1": "FF board design",
  "2.2.2": "FF board testing",
  "2.2.3": "FF board rework",
  "2.3": "Engineering board version (EVT)",
  "2.3.1": "EVT board design",
  "2.3.2": "Board production for SD",
  "2.3.3": "EVT board testing at CVTE",
  "2.3.4": "EVT board architecture rework",
  "2.4": "Design-validation board version (DVT)",
  "2.4.1": "Design",
  "2.4.2": "Production",
  "2.4.3": "Testing",
  "2.4.4": "Rework",
  "2.4.5": "Material calculation",
  "2.5": "Board ready for mass production",
  "2.6": "TV development",
  "2.6.1": "Delivery of boards for TV development",
  "2.6.2": "TV design",
  "2.6.3": "Testing",
  "2.6.4": "Rework",
  "2.7": "TV ready for mass production",
  "2.8": "TV samples",
  "2.8.1": "Board production for CH",
  "2.8.2": "Delivery of boards for manufacturing TV samples",
  "2.8.3": "Production of TV samples",
  "2.8.4": "Delivery to the Moscow office",
  "2.9": "TV samples ready",
  "2.10": "Engineering board samples (EVT)",
  "2.10.1": "Delivery of samples to the Moscow office",
  "2.11": "EVT board samples ready",
  "2.12": "Design-validation board samples (DVT)",
  "2.12.1": "Delivery of samples to the Moscow office",
  "2.13": "DVT board samples ready",
  "2.14": "Hardware ready for mass production",
  "3": "Software",
  "3.1": "HomeOS kick-off",
  "3.2": "Preparation of factory FW requirements",
  "3.2.1": "Alignment of critical factory FW requirements",
  "3.2.2": "SD factory",
  "3.2.3": "Keys, DRM, HDCP",
  "3.2.4": "Self-registration",
  "3.2.5": "OTA",
  "3.2.6": "AT",
  "3.3": "Preparation of TV features",
  "3.3.1": "Ambient",
  "3.3.1.1": "Ambient requirements",
  "3.3.1.2": "Ambient mockups",
  "3.3.1.3": "Implementation choice and minimum technical specification",
  "3.3.1.4": "Full technical specification",
  "3.3.1.5": "Development of the initial Ambient API",
  "3.3.1.6": "Development of the Ambient MP API",
  "3.3.1.7": "Development of the Ambient OTA API",
  "3.3.1.8": "Design of Ambient animations",
  "3.3.1.9": "Ambient controller support",
  "3.3.1.10": "Support in StarOS min",
  "3.3.1.11": "Support in StarOS mid",
  "3.3.1.12": "Support in StarOS max",
  "3.3.2": "ZigBee",
  "3.3.2.1": "ZigBee CVTE",
  "3.3.2.2": "ZigBee min SD",
  "3.3.2.3": "ZigBee MVP SD",
  "3.3.2.4": "ZigBee: agree with CH on testing",
  "3.3.3": "AI PQ",
  "3.3.4": "AI EQ",
  "3.3.5": "DLG 288",
  "3.3.6": "VRR, ALLM, HDMI 2.1",
  "3.4": "All TV features prepared",
  "3.5": "Prepare software release candidate",
  "3.5.1": "Provide the new codebase",
  "3.5.2": "First StarOS build",
  "3.5.3": "Fix initial issues",
  "3.5.4": "Initial regression tests",
  "3.5.5": "Set up the new product in StarOS",
  "3.5.6": "Define the ticket scope for MP",
  "3.5.7": "StarOS version and branch",
  "3.5.8": "Decide application versions",
  "3.5.9": "Create backend groups",
  "3.5.10": "Create SmartApps configs",
  "3.5.11": "Populate configs",
  "3.5.12": "[CVTE] Fix initial bugs",
  "3.5.13": "Decide MP release timing",
  "3.5.14": "[AOSP] Fixes based on the first results",
  "3.5.15": "[SPS/Settings] Fixes based on the first results",
  "3.5.16": "[LS/SS/Push] Fixes based on the first results",
  "3.5.17": "[SUW] Fixes based on the first results",
  "3.5.18": "[Other teams] Fixes based on the first results",
  "3.6": "All initial critical issues and blockers fixed",
  "3.7": "Prepare TV samples",
  "3.8": "Software release",
  "3.8.1": "Regression test planning",
  "3.8.2": "Application regression tests",
  "3.8.3": "Board regression tests",
  "3.8.4": "PEQ and volume curve settings",
  "3.8.5": "Voice processing and activation tests",
  "3.8.6": "Final ticket list",
  "3.8.7": "[CVTE] Regression fixes",
  "3.8.8": "[AOSP] Regression fixes",
  "3.8.9": "[SPS] Regression fixes",
  "3.8.10": "[LS/SS/Push] Regression fixes",
  "3.8.11": "[SUW] Regression fixes",
  "3.8.12": "[Other teams] Regression fixes",
  "3.9": "Go/No-Go",
  "3.10": "Final smoke test",
  "3.11": "Application release",
  "3.12": "MP start",
  "4": "Prepare first OTA",
  "4.1": "Prepare first OTA",
  "4.2": "First OTA ready",
  "5": "New remote control",
  "6": "Marketing",
  "6.1": "Preparation",
  "6.1.1": "Design/Marketing team kick-off",
  "6.1.2": "Receive 3D models from the factory",
  "6.1.3": "Receive renders from the factory",
  "6.1.4": "Positioning of the new TV",
  "6.1.5": "Prepare briefs for landing page, KV, and copywriting",
  "6.2": "Design",
  "6.2.1": "Render editing",
  "6.2.2": "3D model editing",
  "6.2.3": "Develop product cards and rich content",
  "6.2.4": "Landing page",
  "6.2.4.1": "Develop the landing page layout",
  "6.2.4.2": "Align the layout with the TV BU",
  "6.2.4.3": "Landing page development",
  "6.2.4.4": "C-level approval of the landing page",
  "6.2.5": "KV development",
  "6.2.6": "Office indoor",
  "6.2.6.1": "Develop the office indoor animation",
  "6.2.6.2": "Approve the indoor animation",
  "6.2.7": "Design interior renders",
  "6.2.8": "Design the product block for the homepage plus carousel",
  "6.2.9": "Prepare resizes",
  "6.2.10": "Design project ready",
  "6.3": "Videos",
  "6.3.1": "Select the shooting contractor",
  "6.3.2": "Video production",
  "6.3.3": "Video approval",
  "6.4": "Media campaign",
  "6.4.1": "Brief the agency for the media campaign",
  "6.4.2": "Create the media plan",
  "6.4.3": "Prepare SS and banners for MP / Salyut TV",
  "6.4.4": "Prepare a post for TG / Mail",
  "6.5": "PR",
  "6.5.1": "Brief for the PR campaign",
  "6.5.2": "Prepare the pool of media outlets",
  "6.5.3": "Prepare press releases",
  "6.5.4": "Handover of materials for PR launch",
  "6.6": "Handover of marketing materials for launch",
  "6.7": "Start of the marketing campaign",
};

export function wbsEnglishProjectName(projectName: string | null | undefined) {
  if (projectName?.includes("9000")) return "Series 9000";
  return projectName?.trim() || "Project";
}

export function wbsEnglishTitle(
  code: string | null | undefined,
  title: string | null | undefined,
  projectName: string | null | undefined,
) {
  const normalizedCode = code?.trim() ?? "";
  if (projectName?.includes("9000") && SERIES_9000_WBS_TITLE_BY_CODE[normalizedCode]) {
    return SERIES_9000_WBS_TITLE_BY_CODE[normalizedCode];
  }
  return title?.trim() || "";
}
