import type { UserRole } from '@prisma/client';

export const managedRoles: UserRole[] = [
  'ADMIN',
  'PROJECT_MANAGER',
  'EXECUTIVE_VIEWER',
];

export const managedPermissions = [
  'project.read',
  'project.create',
  'project.update',
  'project.close',
  'project.delete',
  'wbs.read',
  'wbs.create',
  'wbs.update',
  'wbs.delete',
  'wbs.move',
  'wbs.baseline',
  'wbs.dependency',
  'issue.read',
  'issue.create',
  'issue.update',
  'issue.close',
  'issue.delete',
  'raid.read',
  'raid.create',
  'raid.update',
  'raid.close',
  'raid.delete',
  'overview.generate',
  'overview.publish',
  'overview.export',
  'admin.users',
  'admin.roles',
  'admin.dictionaries',
  'admin.templates',
  'admin.rag',
  'admin.workflow',
  'admin.jira',
  'admin.health',
  'admin.backup',
  'admin.config',
  'admin.modules',
  'admin.project_access',
  'admin.import',
  'admin.audit',
  'admin.integrations',
];

export const defaultDictionaryItems = [
  ['project_status', 'DRAFT', 'Черновик', 'Проект готовится к запуску', 10],
  ['project_status', 'ACTIVE', 'Активен', 'Проект находится в работе', 20],
  ['project_status', 'ON_HOLD', 'Приостановлен', 'Проект временно остановлен', 30],
  ['project_status', 'CLOSED', 'Закрыт', 'Проект переведен в архив', 40],
  ['project_type', 'PRODUCT', 'Продуктовый', 'Разработка продукта или версии продукта', 10],
  ['project_type', 'IT', 'ИТ', 'Внутренний ИТ-проект', 20],
  ['project_type', 'INTEGRATION', 'Интеграционный', 'Интеграция систем или поставщиков', 30],
  ['project_type', 'HARDWARE', 'Аппаратный', 'Разработка или поставка аппаратной части', 40],
  ['project_type', 'SOFTWARE', 'Программный', 'Разработка программного обеспечения', 50],
  ['risk_type', 'RISK', 'Риск', 'Потенциальное событие с влиянием на проект', 10],
  ['risk_type', 'DEPENDENCY', 'Проблема', 'Фактическая проблема или зависимость', 20],
  ['risk_type', 'ASSUMPTION', 'Допущение', 'Управленческое допущение проекта', 30],
  ['wbs_type', 'PHASE', 'Фаза', 'Верхний уровень структуры проекта', 10],
  ['wbs_type', 'WORK_PACKAGE', 'Пакет работ', 'Группа связанных задач', 20],
  ['wbs_type', 'DELIVERABLE', 'Результат', 'Контрольный результат работ', 30],
  ['wbs_type', 'MILESTONE', 'Веха', 'Нулевая по длительности контрольная точка', 40],
  ['wbs_type', 'GOAL', 'Цель', 'Управленческая цель проекта', 45],
  ['wbs_type', 'TASK', 'Задача', 'Работа с длительностью и исполнителем', 50],
  ['wbs_status', 'NOT_STARTED', 'Не начата', 'Работы еще не стартовали', 10],
  ['wbs_status', 'IN_PROGRESS', 'В работе', 'Работы выполняются', 20],
  ['wbs_status', 'IN_REVIEW', 'На проверке', 'Работа выполнена и ожидает проверки', 30],
  ['wbs_status', 'AT_RISK', 'Под риском', 'Есть риск нарушения срока', 40],
  ['wbs_status', 'BLOCKED', 'Провалено', 'Работа заблокирована или сорвана', 50],
  ['wbs_status', 'DONE', 'Сделано', 'Работа завершена', 60],
  ['wbs_status', 'CANCELLED', 'Отменено', 'Работа исключена из плана', 70],
  ['issue_severity', 'LOW', 'Низкая', 'Низкая критичность', 10],
  ['issue_severity', 'MEDIUM', 'Средняя', 'Средняя критичность', 20],
  ['issue_severity', 'HIGH', 'Высокая', 'Высокая критичность', 30],
  ['issue_severity', 'CRITICAL', 'Критичная', 'Критичная проблема', 40],
  ['raid_type', 'RISK', 'Риск', 'Потенциальное событие с влиянием на проект', 10],
  ['raid_type', 'DEPENDENCY', 'Проблема', 'Фактическая проблема или зависимость', 20],
  ['raid_type', 'ASSUMPTION', 'Допущение', 'Управленческое допущение проекта', 30],
  ['raid_status', 'OPEN', 'Открыто', 'Запись открыта', 10],
  ['raid_status', 'IN_PROGRESS', 'В работе', 'Идет обработка', 20],
  ['raid_status', 'MITIGATED', 'Смягчено', 'Меры снижения выполнены', 30],
  ['raid_status', 'VALIDATED', 'Подтверждено', 'Статус подтвержден', 40],
  ['raid_status', 'BREACHED', 'Нарушено', 'Ограничение или допущение нарушено', 50],
  ['raid_status', 'CLOSED', 'Закрыто', 'Запись закрыта', 60],
] as const;

const defaultWbsTemplates = JSON.stringify(
  [
    {
      code: 'product-release',
      name: 'Запуск продуктовой версии',
      items: [
        { code: '1', level: 1, type: 'PHASE', title: 'Запуск проекта' },
        { code: '1.1', level: 2, type: 'TASK', title: 'Утверждение паспорта проекта' },
        { code: '2', level: 1, type: 'PHASE', title: 'Поставка решения' },
        { code: '2.1', level: 2, type: 'MILESTONE', title: 'Готовность к пилоту' },
      ],
    },
    {
      code: 'integration',
      name: 'Интеграционный проект',
      items: [
        { code: '1', level: 1, type: 'PHASE', title: 'Обследование' },
        { code: '2', level: 1, type: 'PHASE', title: 'Интеграция' },
        { code: '3', level: 1, type: 'PHASE', title: 'Приемка' },
      ],
    },
  ],
  null,
  2,
);

export const defaultSystemSettings = [
  ['jira.enabled', 'false', false],
  ['jira.baseUrl', '', false],
  ['jira.email', '', false],
  ['jira.apiToken', '', true],
  ['jira.maxResults', '100', false],
  ['rag.formula.green', 'Критичных открытых вопросов = 0 AND просроченных задач = 0', false],
  [
    'rag.formula.amber',
    'Есть риски в красной зоне OR отклонение срока <= 10 календарных дней',
    false,
  ],
  ['rag.formula.red', 'Критичный блокер OR отклонение срока > 10 календарных дней', false],
  ['workflow.overview', 'РП -> Спонсор -> Публикация для руководства', false],
  ['workflow.baseline', 'РП -> PMO -> Спонсор', false],
  ['workflow.projectClose', 'РП -> PMO -> Спонсор -> Архив', false],
  ['wbs.templates', defaultWbsTemplates, false],
] as const;

export const integrationSettings = [
  ['gitlab.enabled', 'false', false],
  ['gitlab.baseUrl', '', false],
  ['gitlab.token', '', true],
  ['github.enabled', 'false', false],
  ['github.baseUrl', 'https://api.github.com', false],
  ['github.token', '', true],
  ['azureDevOps.enabled', 'false', false],
  ['azureDevOps.organizationUrl', '', false],
  ['azureDevOps.token', '', true],
  ['bi.enabled', 'false', false],
  ['bi.exportUrl', '', false],
] as const;
