ALTER TABLE "WbsItem"
ADD COLUMN IF NOT EXISTS "predecessor4" TEXT,
ADD COLUMN IF NOT EXISTS "predecessor5" TEXT,
ADD COLUMN IF NOT EXISTS "predecessor6" TEXT;

ALTER TABLE "WbsBaselineItem"
ADD COLUMN IF NOT EXISTS "predecessor4" TEXT,
ADD COLUMN IF NOT EXISTS "predecessor5" TEXT,
ADD COLUMN IF NOT EXISTS "predecessor6" TEXT;
