import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';
import { prisma } from '../../apps/api/src/db.js';
import { createApp } from '../../apps/api/src/server/app.js';
import { hashPassword } from '../../apps/api/src/server/auth.js';

const enabled = process.env.ARTIFACT_TEST_DATABASE === 'true';
test('artifact table and binary attachments round-trip with permissions, conflicts and cleanup', { skip: !enabled }, async () => {
  assert.match(new URL(process.env.DATABASE_URL!).pathname, /test/);
  const suffix = randomUUID().slice(0, 8);
  const unit = await prisma.businessUnit.create({ data: { code: `art-${suffix}`, name: 'Artifacts test' } });
  const user = await prisma.user.create({ data: { email: `art-${suffix}@example.test`, name: 'Artifacts tester', role: 'ADMIN', passwordHash: await hashPassword('test-artifacts-only') } });
  const project = await prisma.project.create({ data: { code: `ART-${suffix}`, name: 'Artifact test', businessUnitId: unit.id, portfolio: 'TEST', sponsor: 'Test', projectManager: 'Test', startDate: new Date(), targetDate: new Date(), budgetPlanned: 0, budgetForecast: 0, summary: '' } });
  const other = await prisma.project.create({ data: { code: `OTHER-${suffix}`, name: 'Other test', businessUnitId: unit.id, portfolio: 'TEST', sponsor: 'Test', projectManager: 'Test', startDate: new Date(), targetDate: new Date(), budgetPlanned: 0, budgetForecast: 0, summary: '' } });
  const server = createApp().listen(0, '127.0.0.1');
  await new Promise<void>(resolve => server.once('listening', resolve));
  const address = server.address();
  assert(address && typeof address !== 'string');
  const base = `http://127.0.0.1:${address.port}`;
  const path = `/api/projects/${project.id}/artifact-table`;
  let cookie = '';
  const request = (url: string, options: RequestInit = {}) => fetch(base + url, { ...options, headers: { Cookie: cookie, 'x-business-unit-id': unit.id, ...options.headers } });
  const put = (body: unknown) => request(path, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
  const upload = (contents: string | Uint8Array, name = 'notes.txt') => { const body = new FormData(); body.append('file', new Blob([typeof contents === 'string' ? contents : new Uint8Array(contents)]), name); return request(path + '/files', { method: 'POST', body }); };
  try {
    assert.equal((await request(path)).status, 401);
    const login = await request('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: user.email, password: 'test-artifacts-only' }) });
    assert.equal(login.status, 200);
    cookie = login.headers.getSetCookie().map(value => value.split(';')[0]).join('; ');
    assert.equal(await (await request(path)).json(), null);
    assert.equal(await prisma.projectArtifactTable.count({ where: { projectId: project.id } }), 0, 'GET must not write');
    const uploaded = await upload('binary test contents', 'Протокол.txt');
    assert.equal(uploaded.status, 201, await uploaded.clone().text());
    const file = await uploaded.json() as { id: string; name: string };
    assert.equal(file.name, 'Протокол.txt');
    assert.deepEqual(Object.keys(file).sort(), ['id', 'name']);
    const download = await request(path + '/files/' + file.id);
    assert.equal(await download.text(), 'binary test contents');
    assert.equal(download.headers.get('content-type'), 'application/octet-stream');
    assert.equal(download.headers.get('x-content-type-options'), 'nosniff');
    assert.match(download.headers.get('content-disposition')!, /attachment; filename\*=UTF-8''/);
    assert.equal((await request(`/api/projects/${other.id}/artifact-table/files/${file.id}`)).status, 404);
    const table = { revision: 0, columns: [{ id: 'date', title: 'Date' }, { id: 'title', title: 'Artifact' }], rows: [{ id: 'first', date: '2026-09-15', cells: { title: 'Uniqueartifactneedle' }, files: { title: [file] } }] };
    const first = await put(table); assert.equal(first.status, 200, await first.clone().text());
    const saved = await first.json(); assert.equal(saved.revision, 1);
    const conflict = await put(table); assert.equal(conflict.status, 409); assert.equal((await conflict.json()).current.revision, 1);
    const concurrent = await Promise.all([put(saved), put(saved)]); assert.deepEqual(concurrent.map(response => response.status).sort(), [200, 409]);
    assert.equal((await request(path + '/files/' + file.id, { method: 'DELETE' })).status, 409);
    const search = await (await request(`/api/search?q=Uniqueartifactneedle&projectId=${project.id}&types=artifact`)).json();
    assert.match(JSON.stringify(search), /Uniqueartifactneedle/);
    const current = await (await request(path)).json();
    current.rows[0].date = '2026-02-30'; assert.equal((await put(current)).status, 400);
    current.rows[0].date = '2026-09-15'; current.rows[0].files = { title: [{ id: 'foreign-file', name: 'no' }] }; assert.equal((await put(current)).status, 400);
    current.rows[0].files = {}; assert.equal((await put(current)).status, 200);
    assert.equal((await request(path + '/files/' + file.id)).status, 404, 'removing reference deletes binary');
    const quotaFile = await prisma.projectArtifactFile.create({ data: { projectId: project.id, name: 'quota-placeholder', size: 30 * 1024 * 1024, data: new Uint8Array([1]) } });
    assert.equal((await upload('over quota')).status, 413);
    await prisma.projectArtifactFile.delete({ where: { id: quotaFile.id } });
    assert.equal((await upload(new Uint8Array(3 * 1024 * 1024 + 1))).status, 413);
    await prisma.project.update({ where: { id: project.id }, data: { status: 'CLOSED' } });
    assert.equal((await upload('closed')).status, 423);
    assert.equal((await put(current)).status, 423);
    await prisma.project.update({ where: { id: project.id }, data: { status: 'ACTIVE' } });
    await prisma.user.update({ where: { id: user.id }, data: { role: 'EXECUTIVE_VIEWER' } });
    assert.equal((await upload('denied')).status, 403);
    assert.equal((await put(current)).status, 403);
  } finally {
    await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve()));
    await prisma.project.deleteMany({ where: { id: { in: [project.id, other.id] } } });
    await prisma.user.delete({ where: { id: user.id } });
    await prisma.businessUnit.delete({ where: { id: unit.id } });
    await prisma.$disconnect();
  }
});
