import {
  JIRA_ANALYTICS_FIELDS_BY_SOURCE,
  jiraSemanticDefaultOutputField,
  type JiraAnalyticsFilterField,
  type JiraSemanticAggregateDefinition,
} from "@pms/shared";

const fields = (...keys: JiraAnalyticsFilterField[]) => keys.map(jiraSemanticDefaultOutputField);

const qualityRules = {
  minimumCoveragePercent: 95,
  maximumRows: 100_000,
  maximumRowsPerIssue: 500,
};

export const JIRA_SEMANTIC_DEFAULT_WIDGETS_VERSION = 6;
export const JIRA_SEMANTIC_WIDGET_IDS_ADDED_IN_VERSION_2 = new Set([
  "active-critical-blocker-risk",
  "retro-critical-blocker-task-sla-45-days",
  "retro-p85-in-progress-to-resolution-by-project",
]);
export const JIRA_SEMANTIC_WIDGET_IDS_ADDED_IN_VERSION_4 = new Set([
  "active-goal-factory-firmware-release",
  "active-goal-first-ota-ready",
]);
export const JIRA_SEMANTIC_WIDGET_IDS_ADDED_IN_VERSION_5 = new Set([
  "active-gitlab-unlinked-branch-commits",
]);
export const JIRA_SEMANTIC_WIDGET_IDS_REPAIRED_IN_VERSION_6 = new Set([
  "active-goal-factory-firmware-release",
  "active-goal-first-ota-ready",
]);

export const JIRA_SYSTEM_SEMANTIC_AGGREGATES: Array<{
  key: string;
  definition: JiraSemanticAggregateDefinition;
}> = [
  {
    key: "issues",
    definition: {
      schemaVersion: 5,
      name: "Тикеты",
      description: "Одна строка на актуальный или восстановленный снимок тикета.",
      grain: "issue",
      basePopulation: { logic: "and", filters: [] },
      rowConfig: { kind: "issue" },
      rowIdentity: ["issueKey"],
      outputFields: fields(...JIRA_ANALYTICS_FIELDS_BY_SOURCE.issues),
      incompleteDataPolicy: "includeWithWarning",
      qualityRules,
      timeZone: "Europe/Moscow",
      asOfSupport: "supported",
    },
  },
  {
    key: "goal-linked-issues",
    definition: {
      schemaVersion: 5,
      name: "Тикеты целей",
      description: "Одна строка на связь цели WBS и тикета, найденную по точному совпадению Jira-лейбла.",
      grain: "goalIssue",
      basePopulation: { logic: "and", filters: [] },
      rowConfig: { kind: "goalIssue" },
      rowIdentity: ["goalId", "issueKey"],
      outputFields: fields(...JIRA_ANALYTICS_FIELDS_BY_SOURCE.goalIssues),
      incompleteDataPolicy: "includeWithWarning",
      qualityRules,
      timeZone: "Europe/Moscow",
      asOfSupport: "supported",
    },
  },
  {
    key: "status-transitions",
    definition: {
      schemaVersion: 5,
      name: "Переходы статусов",
      description: "Одна строка на наблюдённое изменение статуса Jira.",
      grain: "transitionEvent",
      basePopulation: { logic: "and", filters: [] },
      rowConfig: { kind: "transitionEvent" },
      rowIdentity: ["rowId"],
      outputFields: fields(...JIRA_ANALYTICS_FIELDS_BY_SOURCE.transitions),
      incompleteDataPolicy: "exclude",
      qualityRules,
      timeZone: "Europe/Moscow",
      asOfSupport: "none",
    },
  },
  {
    key: "development-activity",
    definition: {
      schemaVersion: 5,
      name: "Активность разработки",
      description: "Одна строка на наблюдённое событие разработки, связанное с тикетом.",
      grain: "developmentEvent",
      basePopulation: { logic: "and", filters: [] },
      rowConfig: { kind: "developmentEvent" },
      rowIdentity: ["rowId"],
      outputFields: fields(...JIRA_ANALYTICS_FIELDS_BY_SOURCE.development),
      incompleteDataPolicy: "exclude",
      qualityRules,
      timeZone: "Europe/Moscow",
      asOfSupport: "none",
    },
  },
  {
    key: "status-intervals",
    definition: {
      schemaVersion: 5,
      name: "Интервалы статусов",
      description: "Одна строка на пару выбранных контрольных точек истории тикета.",
      grain: "interval",
      basePopulation: { logic: "and", filters: [] },
      rowConfig: {
        kind: "interval",
        start: { type: "issueCreated", occurrence: "first" },
        end: {
          type: "statusEntry",
          statuses: [{ id: null, name: "In Progress" }],
          occurrence: "first",
        },
        pairing: "nextAfterStart",
        openIntervals: "include",
      },
      rowIdentity: ["rowId"],
      outputFields: fields(...JIRA_ANALYTICS_FIELDS_BY_SOURCE.statusIntervals),
      incompleteDataPolicy: "exclude",
      qualityRules,
      timeZone: "Europe/Moscow",
      asOfSupport: "none",
    },
  },
  {
    key: "critical-blocker-sla",
    definition: {
      schemaVersion: 5,
      name: "SLA Critical/Blocker",
      description: "Интервал от создания или первого повышения до Critical/Blocker до Resolution.",
      grain: "interval",
      basePopulation: { logic: "and", filters: [] },
      rowConfig: {
        kind: "criticalSla",
        issueTypes: ["Bug", "Bug Report", "Defect", "Баг", "Ошибка", "Дефект"],
        priorities: ["Critical", "Blocker"],
        startPolicy: "createdOrFirstPriorityEntry",
        endAnchor: "resolution",
        requirePriorityAtResolution: true,
        openIntervals: "include",
      },
      rowIdentity: ["rowId"],
      outputFields: fields(...JIRA_ANALYTICS_FIELDS_BY_SOURCE.criticalBugs),
      incompleteDataPolicy: "exclude",
      qualityRules,
      timeZone: "Europe/Moscow",
      asOfSupport: "supported",
    },
  },
  {
    key: "critical-blocker-task-sla",
    definition: {
      schemaVersion: 5,
      name: "SLA задач Critical/Blocker",
      description: "Задачи Critical/Blocker: интервал от создания или первого повышения приоритета до Resolution.",
      grain: "interval",
      basePopulation: { logic: "and", filters: [] },
      rowConfig: {
        kind: "criticalSla",
        issueTypes: ["Task", "Задача"],
        priorities: ["Critical", "Blocker"],
        startPolicy: "createdOrFirstPriorityEntry",
        endAnchor: "resolution",
        requirePriorityAtResolution: true,
        openIntervals: "include",
      },
      rowIdentity: ["rowId"],
      outputFields: fields(...JIRA_ANALYTICS_FIELDS_BY_SOURCE.criticalBugs),
      incompleteDataPolicy: "exclude",
      qualityRules,
      timeZone: "Europe/Moscow",
      asOfSupport: "supported",
    },
  },
  {
    key: "critical-blocker-risk",
    definition: {
      schemaVersion: 5,
      name: "Тикеты Critical/Blocker под риском",
      description: "Нерешённые баги в семидневном окне до SLA 30 дней и задачи старше 28 дней от начала Critical/Blocker.",
      grain: "interval",
      basePopulation: { logic: "and", filters: [] },
      rowConfig: {
        kind: "criticalRisk",
        priorities: ["Critical", "Blocker"],
        bugIssueTypes: ["Bug", "Bug Report", "Defect", "Баг", "Ошибка", "Дефект"],
        bugSlaHours: 720,
        bugWarningHours: 168,
        taskIssueTypes: ["Task", "Задача"],
        taskRiskHours: 672,
      },
      rowIdentity: ["rowId"],
      outputFields: fields(...JIRA_ANALYTICS_FIELDS_BY_SOURCE.criticalBugs),
      incompleteDataPolicy: "exclude",
      qualityRules,
      timeZone: "Europe/Moscow",
      asOfSupport: "none",
    },
  },
  {
    key: "in-progress-resolution",
    definition: {
      schemaVersion: 5,
      name: "От первого In Progress до Resolution",
      description: "Одна строка на завершённый интервал от первого входа в In Progress до Resolution.",
      grain: "interval",
      basePopulation: { logic: "and", filters: [] },
      rowConfig: {
        kind: "interval",
        start: {
          type: "statusEntry",
          statuses: [{ id: null, name: "In Progress" }],
          occurrence: "first",
        },
        end: { type: "resolution", occurrence: "first" },
        pairing: "nextAfterStart",
        openIntervals: "exclude",
      },
      rowIdentity: ["rowId"],
      outputFields: fields(...JIRA_ANALYTICS_FIELDS_BY_SOURCE.statusIntervals),
      incompleteDataPolicy: "exclude",
      qualityRules,
      timeZone: "Europe/Moscow",
      asOfSupport: "none",
    },
  },
  {
    key: "gitlab-branch-commits",
    definition: {
      schemaVersion: 5,
      name: "Коммиты ветки GitLab",
      description: "Достижимые из выбранной ветки коммиты за период по дате самого коммита. Связь с Jira определяется по существующему ключу в сообщении коммита или связанном MR.",
      grain: "gitlabCommit",
      basePopulation: { logic: "and", filters: [] },
      rowConfig: {
        kind: "gitlabBranchCommit",
        projectPath: "athena/staros",
        targetBranch: "factory-1.103-cvte968",
        lookbackDays: 14,
        includeMergeCommits: false,
      },
      rowIdentity: ["gitlabProjectPath", "gitlabTargetBranch", "commitSha"],
      outputFields: fields(...JIRA_ANALYTICS_FIELDS_BY_SOURCE.gitlabCommits),
      incompleteDataPolicy: "exclude",
      qualityRules: { minimumCoveragePercent: 100, maximumRows: 2_000, maximumRowsPerIssue: 1 },
      timeZone: "Europe/Moscow",
      asOfSupport: "none",
    },
  },
  {
    key: "cvte968-mp-unresolved",
    definition: {
      schemaVersion: 5,
      name: "Нерешённые тикеты MP",
      description: "Тикеты с метками cvte968 и MP, кроме Epic и Story, без Resolution и вне статуса Cancelled.",
      grain: "issue",
      basePopulation: {
        logic: "and",
        filters: [
          { id: "cvte968-mp-label-cvte968", field: "labels", operator: "equals", value: "cvte968" },
          { id: "cvte968-mp-label-mp", field: "labels", operator: "equals", value: "mp" },
          { id: "cvte968-mp-not-epic", field: "issueType", operator: "notEquals", value: "Epic" },
          { id: "cvte968-mp-not-story", field: "issueType", operator: "notEquals", value: "Story" },
          { id: "cvte968-mp-resolution-empty", field: "resolution", operator: "empty", value: "" },
          { id: "cvte968-mp-not-cancelled", field: "status", operator: "notEquals", value: "Cancelled" },
        ],
      },
      rowConfig: { kind: "issue" },
      rowIdentity: ["issueKey"],
      outputFields: fields(...JIRA_ANALYTICS_FIELDS_BY_SOURCE.issues),
      incompleteDataPolicy: "includeWithWarning",
      qualityRules,
      timeZone: "Europe/Moscow",
      asOfSupport: "supported",
    },
  },
];
