import {
  JIRA_SEMANTIC_COLUMN_WIDTH_MAX,
  JIRA_SEMANTIC_COLUMN_WIDTH_MIN,
  jiraAnalyticsFilterFields,
  jiraAnalyticsFilterOperators,
  jiraAnalyticsGroupings,
  jiraAnalyticsMetrics,
  jiraAnalyticsSortDirections,
  jiraAnalyticsSortFields,
  jiraSemanticAggregateGrains,
} from "@pms/shared";

const jiraAnalyticsOpenApiFields = jiraAnalyticsFilterFields;

export const openApiComponents = {
    securitySchemes: {
      sessionCookie: {
        type: "apiKey",
        in: "cookie",
        name: "pms_session",
      },
      bearerApiToken: {
        type: "http",
        scheme: "bearer",
        bearerFormat: "pms_* API token",
      },
    },
    schemas: {
      Error: {
        type: "object",
        properties: {
          error: { type: "string" },
        },
        required: ["error"],
      },
      JiraHistoryAggregate: {
        type: "object",
        required: ["versions", "tickets", "payloadBytes", "averageBytes", "p95Bytes", "incompleteHydration", "attachmentReferencesStripped"],
        properties: {
          versions: { type: "integer" },
          tickets: { type: "integer" },
          payloadBytes: { type: "integer" },
          averageBytes: { type: "integer" },
          p95Bytes: { type: "integer" },
          incompleteHydration: { type: "integer" },
          attachmentReferencesStripped: { type: "integer" },
        },
      },
      JiraAnalyticsFilter: {
        type: "object",
        additionalProperties: false,
        properties: {
          id: { type: "string", minLength: 1, maxLength: 200 },
          field: {
            type: "string",
            enum: jiraAnalyticsOpenApiFields,
          },
          operator: {
            type: "string",
            enum: jiraAnalyticsFilterOperators,
          },
          value: { type: "string", maxLength: 1000 },
        },
        required: ["id", "field", "operator", "value"],
      },
      JiraSemanticAggregateDefinition: {
        type: "object",
        additionalProperties: false,
        properties: {
          schemaVersion: { type: "integer", const: 5 },
          name: { type: "string", minLength: 1, maxLength: 200 },
          description: { type: "string", maxLength: 1000 },
          grain: { type: "string", enum: jiraSemanticAggregateGrains },
          basePopulation: {
            type: "object",
            additionalProperties: false,
            properties: {
              logic: { type: "string", enum: ["and", "or"] },
              filters: { type: "array", maxItems: 30, items: { $ref: "#/components/schemas/JiraAnalyticsFilter" } },
            },
            required: ["logic", "filters"],
          },
          rowConfig: { type: "object" },
          rowIdentity: { type: "array", minItems: 1, maxItems: 10, uniqueItems: true, items: { type: "string", enum: ["rowId", ...jiraAnalyticsOpenApiFields] } },
          outputFields: {
            type: "array",
            minItems: 1,
            maxItems: jiraAnalyticsOpenApiFields.length,
            uniqueItems: true,
            items: {
              type: "object",
              additionalProperties: false,
              properties: {
                key: { type: "string", enum: jiraAnalyticsOpenApiFields },
                label: { type: "string", minLength: 1, maxLength: 200 },
                type: { type: "string", enum: ["text", "number", "boolean", "date", "url"] },
                nullable: { type: "boolean" },
              },
              required: ["key", "label", "type", "nullable"],
            },
          },
          incompleteDataPolicy: { type: "string", enum: ["exclude", "includeWithWarning"] },
          qualityRules: {
            type: "object",
            additionalProperties: false,
            properties: {
              minimumCoveragePercent: { type: "number", minimum: 0, maximum: 100 },
              maximumRows: { type: "integer", minimum: 1, maximum: 1000000 },
              maximumRowsPerIssue: { type: "integer", minimum: 1, maximum: 10000 },
            },
            required: ["minimumCoveragePercent", "maximumRows", "maximumRowsPerIssue"],
          },
          timeZone: { type: "string", enum: ["Europe/Moscow", "UTC"] },
          asOfSupport: { type: "string", enum: ["none", "supported"] },
        },
        required: ["schemaVersion", "name", "description", "grain", "basePopulation", "rowConfig", "rowIdentity", "outputFields", "incompleteDataPolicy", "qualityRules", "timeZone", "asOfSupport"],
      },
      JiraSemanticWidget: {
        type: "object",
        additionalProperties: false,
        properties: {
          id: { type: "string", minLength: 1, maxLength: 200 },
          title: { type: "string", minLength: 1, maxLength: 200 },
          aggregateId: { type: "string", minLength: 1, maxLength: 200 },
          aggregateVersion: { type: "integer", minimum: 1 },
          placement: { type: "string", enum: ["active", "retro"] },
          selectedFields: { type: "array", minItems: 1, maxItems: jiraAnalyticsOpenApiFields.length, uniqueItems: true, items: { type: "string", enum: jiraAnalyticsOpenApiFields } },
          columnWidths: {
            type: "object",
            additionalProperties: { type: "integer", minimum: JIRA_SEMANTIC_COLUMN_WIDTH_MIN, maximum: JIRA_SEMANTIC_COLUMN_WIDTH_MAX },
            propertyNames: { enum: jiraAnalyticsOpenApiFields },
          },
          filterLogic: { type: "string", enum: ["and", "or"] },
          filters: { type: "array", maxItems: 30, items: { $ref: "#/components/schemas/JiraAnalyticsFilter" } },
          dateField: { type: ["string", "null"], enum: [...jiraAnalyticsOpenApiFields, null] },
          asOf: { type: ["string", "null"], format: "date-time" },
          metric: { type: "string", enum: jiraAnalyticsMetrics },
          groupBy: { type: "string", enum: jiraAnalyticsGroupings },
          sortBy: { type: "string", enum: jiraAnalyticsSortFields },
          sortDirection: { type: "string", enum: jiraAnalyticsSortDirections },
          visualization: { type: "string", enum: ["number", "bar", "table"] },
          width: { type: "string", enum: ["half", "full"] },
        },
        required: ["id", "title", "aggregateId", "aggregateVersion", "placement", "selectedFields", "filterLogic", "filters", "dateField", "asOf", "metric", "groupBy", "sortBy", "sortDirection", "visualization", "width"],
      },
      JiraSemanticDashboard: {
        type: "object",
        additionalProperties: false,
        properties: {
          version: { type: "integer", const: 5 },
          periodDays: { type: "integer", enum: [30, 90, 180, 365] },
          assignee: { type: "string", maxLength: 200 },
          widgets: { type: "array", maxItems: 100, items: { $ref: "#/components/schemas/JiraSemanticWidget" } },
        },
        required: ["version", "periodDays", "assignee", "widgets"],
      },
      JiraSemanticQuery: {
        type: "object",
        additionalProperties: false,
        properties: {
          aggregateVersion: { type: "integer", minimum: 1 },
          selectedFields: { type: "array", minItems: 1, maxItems: jiraAnalyticsOpenApiFields.length, uniqueItems: true, items: { type: "string", enum: jiraAnalyticsOpenApiFields } },
          metric: { type: "string", enum: jiraAnalyticsMetrics },
          groupBy: { type: "string", enum: jiraAnalyticsGroupings },
          filters: { type: "array", maxItems: 30, items: { $ref: "#/components/schemas/JiraAnalyticsFilter" } },
          filterLogic: { type: "string", enum: ["and", "or"] },
          periodDays: { type: ["integer", "null"], enum: [30, 90, 180, 365, null] },
          dateField: { type: ["string", "null"], enum: [...jiraAnalyticsOpenApiFields, null] },
          assignee: { type: "string", maxLength: 200 },
          sortBy: { type: "string", enum: jiraAnalyticsSortFields },
          sortDirection: { type: "string", enum: jiraAnalyticsSortDirections },
          page: { type: "integer", minimum: 1, maximum: 100000 },
          pageSize: { type: "integer", minimum: 1, maximum: 100 },
          groupKey: { type: "string", maxLength: 500 },
          asOf: { type: ["string", "null"], format: "date-time" },
        },
        required: ["aggregateVersion", "selectedFields", "metric", "groupBy", "filters", "filterLogic", "periodDays", "dateField", "assignee", "sortBy", "sortDirection"],
      },
      JiraAggregateEvaluationResult: {
        type: "object",
        properties: {
          evaluatedAt: { type: "string", format: "date-time" },
          effective: { type: "object" },
          value: { type: "number" },
          groups: { type: "array", items: { type: "object" } },
          records: { type: "array", items: { type: "object" } },
          totalRecords: { type: "integer", minimum: 0 },
          page: { type: "integer", minimum: 1, maximum: 100000 },
          pageSize: { type: "integer", minimum: 1, maximum: 100 },
          quality: { $ref: "#/components/schemas/JiraAnalyticsDataQuality" },
          reconstruction: { $ref: "#/components/schemas/JiraAsOfReconstruction" },
        },
        required: ["evaluatedAt", "effective", "value", "groups", "records", "totalRecords", "page", "pageSize", "quality"],
      },
      JiraAnalyticsDataQuality: {
        type: "object",
        additionalProperties: false,
        properties: {
          status: { type: "string", enum: ["COMPLETE", "PARTIAL", "NO_DATA", "UNAVAILABLE"] },
          basis: { type: "string", enum: ["CURRENT_PROJECTION", "OBSERVED_VERSIONS"] },
          source: { type: "string", enum: ["issues", "goalIssues", "transitions", "development", "criticalBugs", "statusIntervals", "gitlabCommits"] },
          population: { type: "integer", minimum: 0 },
          complete: { type: "integer", minimum: 0 },
          incomplete: { type: "integer", minimum: 0 },
          coveragePercent: { type: ["number", "null"], minimum: 0, maximum: 100 },
          oldestObservedAt: { type: ["string", "null"], format: "date-time" },
          latestObservedAt: { type: ["string", "null"], format: "date-time" },
          warnings: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              properties: {
                code: {
                  type: "string",
                  enum: [
                    "NO_SOURCE_POPULATION", "INCOMPLETE_TRANSITION_HISTORY", "MISSING_ISSUE_CREATED_AT",
                    "INCOMPLETE_DEVELOPMENT_DATA", "INCOMPLETE_CRITICAL_SLA", "UNDETERMINED_JIRA_LINK",
                    "MISSING_HISTORICAL_OBSERVATION", "BEFORE_HISTORY_START", "HISTORY_WRITE_GAP",
                  ],
                },
                count: { type: "integer", minimum: 0 },
              },
              required: ["code", "count"],
            },
          },
        },
        required: [
          "status", "basis", "source", "population", "complete", "incomplete",
          "coveragePercent", "oldestObservedAt", "latestObservedAt", "warnings",
        ],
      },
      JiraAsOfReconstruction: {
        type: "object",
        additionalProperties: false,
        properties: {
          mode: { type: "string", const: "AS_OF" },
          provenance: { type: "string", const: "RECONSTRUCTED" },
          basis: { type: "string", const: "OBSERVED_VERSIONS" },
          asOf: { type: "string", format: "date-time" },
          tickets: { type: "integer", minimum: 0 },
          ticketsWithoutObservation: { type: "integer", minimum: 0 },
          ticketsRetiredAfterAsOf: { type: "integer", minimum: 0 },
          versionRowsScanned: { type: "integer", minimum: 0, maximum: 200000 },
          earliestObservationAt: { type: ["string", "null"], format: "date-time" },
          stalenessHours: {
            oneOf: [
              { type: "null" },
              {
                type: "object",
                additionalProperties: false,
                properties: {
                  p50: { type: "number", minimum: 0 },
                  p95: { type: "number", minimum: 0 },
                  max: { type: "number", minimum: 0 },
                },
                required: ["p50", "p95", "max"],
              },
            ],
          },
          beforeHistoryStart: { type: "boolean" },
          historyWriteGap: {
            type: "object",
            additionalProperties: false,
            properties: {
              includesAsOf: { type: "boolean" },
              runs: { type: "integer", minimum: 0 },
              firstAt: { type: ["string", "null"], format: "date-time" },
              lastAt: { type: ["string", "null"], format: "date-time" },
            },
            required: ["includesAsOf", "runs", "firstAt", "lastAt"],
          },
          quality: {
            type: "string",
            enum: ["AVAILABLE", "UNAVAILABLE_HISTORY_WRITE_GAP"],
          },
        },
        required: [
          "mode", "provenance", "basis", "asOf", "tickets", "ticketsWithoutObservation",
          "ticketsRetiredAfterAsOf", "versionRowsScanned", "earliestObservationAt",
          "stalenessHours", "beforeHistoryStart", "historyWriteGap", "quality",
        ],
      },
      JiraAnalyticsFacets: {
        type: "object",
        additionalProperties: false,
        properties: {
          issueCount: { type: "integer", minimum: 0 },
          activeIssueCount: { type: "integer", minimum: 0 },
          transitionHistoryCompleteCount: { type: "integer", minimum: 0 },
          developmentDataAvailableCount: { type: "integer", minimum: 0 },
          criticalSlaTrackedCount: { type: "integer", minimum: 0 },
          criticalSlaReadyCount: { type: "integer", minimum: 0 },
          latestSyncedAt: { type: ["string", "null"], format: "date-time" },
          assignees: { type: "array", maxItems: 500, items: { type: "string" } },
          assigneesTruncated: { type: "boolean" },
        },
        required: [
          "issueCount", "activeIssueCount", "transitionHistoryCompleteCount",
          "developmentDataAvailableCount", "criticalSlaTrackedCount", "criticalSlaReadyCount",
          "latestSyncedAt", "assignees", "assigneesTruncated",
        ],
      },
      Project: {
        type: "object",
        properties: {
          id: { type: "string" },
          code: { type: "string" },
          name: { type: "string" },
          status: { type: "string", enum: ["DRAFT", "ACTIVE", "ON_HOLD", "CLOSED"] },
          rag: { type: "string", enum: ["GREEN", "AMBER", "RED"] },
          projectManager: { type: "string" },
          startDate: { type: "string", format: "date-time" },
          initialTargetDate: { type: ["string", "null"], format: "date-time" },
          targetDate: { type: "string", format: "date-time" },
          progress: { type: "integer", minimum: 0, maximum: 100 },
          scheduleVariance: { type: "integer" },
        },
        required: ["id", "code", "name", "status"],
      },
      WbsItem: {
        type: "object",
        properties: {
          id: { type: "string" },
          projectId: { type: "string" },
          code: { type: "string" },
          title: { type: "string" },
          type: {
            type: "string",
            enum: ["PHASE", "WORK_PACKAGE", "DELIVERABLE", "MILESTONE", "GOAL", "TASK"],
          },
          status: {
            type: "string",
            enum: ["NOT_STARTED", "IN_PROGRESS", "IN_REVIEW", "AT_RISK", "BLOCKED", "DONE", "CANCELLED"],
          },
          owner: { type: "string" },
          startDate: { type: ["string", "null"], format: "date-time" },
          dueDate: { type: ["string", "null"], format: "date-time" },
          predecessor1: { type: ["string", "null"] },
          predecessor2: { type: ["string", "null"] },
          predecessor3: { type: ["string", "null"] },
          predecessor4: { type: ["string", "null"] },
          predecessor5: { type: ["string", "null"] },
          predecessor6: { type: ["string", "null"] },
          calendarCode: { type: "string", enum: ["RU", "CN", "RU_CN"] },
          effortPercent: { type: "integer", minimum: 0, maximum: 100 },
          jiraTicketKey: { type: ["string", "null"] },
          jiraTicketUrl: { type: ["string", "null"], format: "uri" },
          mattermostUrl: { type: ["string", "null"], format: "uri" },
          comment: { type: ["string", "null"] },
        },
        required: ["id", "projectId", "code", "title", "type", "status"],
      },
      WbsDependency: {
        type: "object",
        properties: {
          id: { type: "string" },
          projectId: { type: "string" },
          predecessorId: { type: "string" },
          successorId: { type: "string" },
          type: { type: "string", enum: ["FS", "SS", "FF", "SF"] },
          lagDays: { type: "integer" },
        },
        required: ["id", "projectId", "predecessorId", "successorId", "type"],
      },
      OpenIssue: {
        type: "object",
        properties: {
          id: { type: "string" },
          projectId: { type: "string" },
          phaseId: { type: ["string", "null"] },
          workPackageId: { type: ["string", "null"] },
          riskId: { type: ["string", "null"] },
          category: { type: "string" },
          title: { type: "string" },
          referenceLabel: { type: "string" },
          referenceUrl: { type: ["string", "null"], format: "uri" },
          severity: { type: "string", enum: ["LOW", "MEDIUM", "HIGH", "CRITICAL"] },
          readiness: { type: "string", enum: ["RED", "AMBER", "GREEN"] },
          status: { type: "string" },
          owner: { type: "string" },
          impact: { type: "string" },
          dueDate: { type: ["string", "null"], format: "date-time" },
          jiraTicketKey: { type: ["string", "null"] },
          jiraTicketUrl: { type: ["string", "null"], format: "uri" },
          decisionRequired: { type: "boolean" },
          threadLinks: {
            type: "array",
            items: { $ref: "#/components/schemas/IssueThreadLink" },
          },
          statusUpdates: {
            type: "array",
            items: { $ref: "#/components/schemas/IssueStatusUpdate" },
          },
        },
        required: [
          "id",
          "projectId",
          "phaseId",
          "workPackageId",
          "riskId",
          "category",
          "title",
          "referenceLabel",
          "severity",
          "readiness",
          "status",
          "owner",
          "impact",
        ],
      },
      IssueThreadLink: {
        type: "object",
        properties: {
          id: { type: "string" },
          issueId: { type: "string" },
          threadUrl: { type: "string", format: "uri" },
          createdAt: { type: "string", format: "date-time" },
        },
        required: ["id", "issueId", "threadUrl", "createdAt"],
      },
      IssueStatusUpdate: {
        type: "object",
        properties: {
          id: { type: "string" },
          issueId: { type: "string" },
          statusAt: { type: "string", format: "date-time" },
          text: { type: "string" },
          createdAt: { type: "string", format: "date-time" },
          updatedAt: { type: "string", format: "date-time" },
        },
        required: ["id", "issueId", "statusAt", "text"],
      },
      RaidItem: {
        type: "object",
        properties: {
          id: { type: "string" },
          projectId: { type: "string" },
          type: { type: "string", enum: ["RISK", "ASSUMPTION", "DEPENDENCY"] },
          title: { type: "string" },
          owner: { type: "string" },
          status: {
            type: "string",
            enum: ["OPEN", "IN_PROGRESS", "MITIGATED", "VALIDATED", "BREACHED", "CLOSED"],
          },
          riskScore: { type: "integer" },
          jiraTicketKey: { type: ["string", "null"] },
          jiraTicketUrl: { type: ["string", "null"], format: "uri" },
        },
        required: ["id", "projectId", "type", "title", "status"],
      },
    },
} as const;
