#!/usr/bin/env sh

TARGET="${PRISMA_CLI_BINARY_TARGETS:-debian-openssl-3.0.x}"

export PRISMA_CLI_BINARY_TARGETS="$TARGET"
export PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING="${PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING:-1}"
export PRISMA_ENGINES_DIR="${PRISMA_ENGINES_DIR:-/tmp/prisma-engines}"
export PRISMA_ENGINES_JOB_TOKEN="${PRISMA_ENGINES_JOB_TOKEN:-${CI_JOB_TOKEN:-}}"
export PRISMA_ENGINES_BASE_URL="${PRISMA_ENGINES_BASE_URL:-}"
export PRISMA_SCHEMA_ENGINE_BINARY="${PRISMA_SCHEMA_ENGINE_BINARY:-${PRISMA_ENGINES_DIR}/schema-engine-${TARGET}}"
export PRISMA_QUERY_ENGINE_LIBRARY="${PRISMA_QUERY_ENGINE_LIBRARY:-${PRISMA_ENGINES_DIR}/libquery_engine-${TARGET}.so.node}"
